{% set name = "xorg-font-util" %}
{% set version = "1.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.freedesktop.org/xorg/font/util/-/archive/font-util-{{ version }}/util-font-util-{{ version }}.tar.gz
  sha256: f0129159515c13ebe53ba2a6a94755e98c266470e844ee0aacc6196fd62b44f0

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - pkg-config
    - make
    - autoconf
    - automake
    - xorg-macros

test:
  requires:
    - pkg-config
  commands:
    - pkg-config --exists fontutil

about:
  home: https://www.x.org/
  summary: X.Org font package creation/installation utilities
  description: X.Org font package creation/installation utilities
  license: MIT
  license_family: MIT
  license_file: COPYING
  dev_url: https://gitlab.freedesktop.org/xorg/font/util
  doc_url: https://www.x.org/wiki/Documentation/

extra:
  recipe-maintainers:
    - ViridianMelody
